# Generated by Django 4.0.6 on 2022-08-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetaction',
            name='action',
            field=models.CharField(choices=[(1, 'Retweet'), (2, 'Like'), (3, 'Comment')], max_length=2),
        ),
    ]
