# Generated by Django 4.0.6 on 2022-08-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_remove_tweet_likes_tweet_likes_remove_tweet_retweets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetaction',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='twitter.tweet'),
        ),
    ]
