# Generated by Django 4.0.6 on 2022-08-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter_user',
            new_name='user',
        ),
    ]
