# Generated by Django 4.0.6 on 2022-08-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_twitter_user_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
